"""The agent's contract (SPEC 4.1), and validation of a ``run`` against it.

``describe`` answers *what does this agent take, and what does it give
back* — the document that lets a client render an agent it has never seen
without a line of per-listing code. It **MUST** be side-effect free and
answerable with no credentials and no entitlement (SPEC 4.1), which is
also what makes conformance Level 1 useful: an agent nobody can run can
still describe itself.

**Where the document comes from, and why there are two answers.**

A conforming ``describe`` is generated by the distributor from the listing
record — the publish-wizard fields, the declared setup variables, the
captured example run — and shipped inside the bundle as ``postern.json``.
That is the half a generic runner cannot reproduce: nothing on the buyer's
disk knows the listing's title, its version, its seller, or what a good
run looked like.

Every bundle published before that generator existed carries no
``postern.json``, though, and they are on buyers' disks now. A runner that
refuses them is a runner that works for nobody today, so this module
derives a document from what the bundle *does* carry: the reserved
``prompt`` key, the buyer's own ``variables.json`` keys, the tools the
loader resolves from ``config/``, and the credentials ``.env.example``
declares. The derived form is deliberately thinner rather than invented —
:data:`DERIVED_AGENT_NAME` says so in the agent's own name, and no
``examples`` are fabricated.

**The identifier is the one thing no bundle can carry.** SPEC 1.5 makes an
agent id ``{owner}/{name}``, unique within a distributor and compared
octet-for-octet, and guessing one produces a string that looks like an
identifier and addresses somebody else's listing. It is also, with the
buyer's token, one of exactly two things this runner needs from the
distributor and cannot derive — so both travel with the purchase rather
than inside an artifact, and ``POSTERN_AGENT_ID`` is where the runner
reads it.

Until it is given one, a runner still owes ``describe`` an ``agent.id``:
the field is REQUIRED. SPEC 5.1 is what makes that answerable —
"an agent with no distributor still has one, which is not required to be
unique anywhere" — so an unconfigured runner reports
:data:`LOCAL_ID_OWNER`/``<digest of this bundle>``. It is stable per
bundle, grammatically valid, and visibly local. **Nothing addresses a
distributor with it**: ``entitlement.py`` reads ``POSTERN_AGENT_ID`` and
never this document, so a local identity can never become an entitlement
check for the wrong listing.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

from sigrix_runtime.postern import POSTERN_VERSION

if TYPE_CHECKING:
    # Annotation-only: a real import here would defeat the point of the
    # local imports below. `from __future__ import annotations`
    # defers evaluation of the annotations themselves, but a static reader
    # still needs the name bound somewhere.
    from sigrix_runtime import execution
from sigrix_runtime.postern.errors import PosternError, bad_request

# The file a Sigrix bundle carries its generated contract in. Read verbatim
# — a runner that "fixed up" a distributor's document would be answering a
# question the distributor had already answered, differently.
DESCRIBE_FILENAME = "postern.json"
# The Agent Plugins manifest the platform writes beside it; its
# ``extensions["org.sigrix"]`` block is where distributor facts ride (§8).
MANIFEST_FILENAME = "plugin.json"
_MANIFEST_NAMESPACE = "org.sigrix"

DERIVED_AGENT_NAME = "This bundle (described from its own files)"

# The owner part of a bundle's local identity, for a runner no distributor
# has named (see the module docstring). Deliberately not a seller handle
# and deliberately not spellable as one: SPEC 1.5's grammar admits it, and
# no Sigrix identifier can collide with it because no username is "local".
LOCAL_ID_OWNER = "local"

# Files whose bytes make one bundle a different agent from another. The
# manifest is preferred where it exists — it is a digest of the whole
# reviewed file set already — and the config is what is left when a folder
# has been unzipped and edited.
_IDENTITY_SOURCES = (".bundle_sha256", "config/agents.yaml", "config/tasks.yaml", "config/workforce.yaml")

# SPEC 1.5, as the schemas spell it.
_AGENT_ID_PATTERN = re.compile(r"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?/[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$")
_AGENT_ID_MAX_LENGTH = 128

#: What an identifier is, in the words every refusal of a malformed one uses.
AGENT_ID_SHAPE = (
    "two parts, '{seller-handle}/{listing-id}', written in lowercase letters, digits, '-' and '.', "
    "128 characters at most (SPEC 1.5)"
)

# SPEC 4.1.1: the whole value space of v0. A client treats an unrecognised
# type as text; a runner may not emit one.
_INPUT_TYPES = ("text", "number", "select")

# Which of the starter's sandboxed tools reach past the workspace or spend
# money (SPEC 4.1.2). ``file_read`` is scoped to ``workspace/`` and is
# repeatable; ``file_write`` mutates it; the search tools spend a provider's
# credit per call. This is the only safety-relevant field in ``describe``,
# and it is a subset of ``tools`` rather than a second list.
#
# Public because the distributor's generator imports **this** constant
# rather than keeping its own copy. A generated document and a derived one
# disagreeing about which tools are dangerous is the mirrored-constant
# failure with a safety field in it, so there is one list and it lives
# beside the sandbox that implements it.
WRITE_TOOLS = frozenset({"file_write", "web_search", "serper_search"})

_ENV_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=")
_ENV_COMMENT = re.compile(r"^#\s*([A-Za-z_][A-Za-z0-9_]*)\s*[—–-]\s*(.*)$")
_SIGNUP_LINE = re.compile(r"^#\s*Get one at\s+(\S+)")


def load_describe(bundle_root: Path, *, agent_id: str = "") -> dict[str, Any]:
    """The bundle's ``describe`` document: shipped if present, else derived.

    ``agent_id`` overrides whatever the shipped document carries. It exists
    for the container case, where the same image serves whichever listing
    it was pointed at and the operator knows which one; a bundle that
    already names itself correctly is unaffected, because the value passed
    in is the one the entitlement check resolved.
    """
    shipped = _read_shipped(bundle_root)
    document = shipped if shipped is not None else derive_describe(bundle_root)
    agent = document.setdefault("agent", {})
    if agent_id:
        agent["id"] = agent_id
    if not is_agent_id(str(agent.get("id") or "")):
        # Absent, or not an identifier at all -- an embedder's config, a
        # hand-edited postern.json. SPEC 1.5 is a MUST on every payload that
        # carries one, so a malformed id was emitted by nothing, and
        # ``__main__`` refuses a malformed POSTERN_AGENT_ID at boot.
        agent["id"] = local_agent_id(bundle_root)
    document["postern"] = POSTERN_VERSION
    return document


def local_agent_id(bundle_root: Path) -> str:
    """This bundle's local identity — stable, valid, and visibly not a listing."""
    digest = hashlib.sha256()
    for name in _IDENTITY_SOURCES:
        try:
            digest.update((bundle_root / name).read_bytes())
        except OSError:
            continue
    return f"{LOCAL_ID_OWNER}/{digest.hexdigest()[:12]}"


def listing_url(bundle_root: Path) -> str:
    """The listing's page on its distributor, from ``plugin.json``, or ``""``.

    The one address a refused buyer can be sent to that names no cause.
    It is the bundle's own static knowledge — ``plugin.json`` is the
    platform's projection of this same describe document — and it is read
    defensively: a bundle that ships none, or one edited into something that
    is not an ``http(s)`` URL, answers nothing rather than a string a client
    would render as a link.
    """
    try:
        raw = json.loads((bundle_root / MANIFEST_FILENAME).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ""
    extensions = raw.get("extensions") if isinstance(raw, dict) else None
    sigrix = extensions.get(_MANIFEST_NAMESPACE) if isinstance(extensions, dict) else None
    url = str(sigrix.get("listing_url") or "").strip() if isinstance(sigrix, dict) else ""
    if not url.startswith(("https://", "http://")) or any(ch.isspace() for ch in url):
        return ""
    return url


def declared_credentials(document: dict[str, Any]) -> list[str]:
    """The environment-variable names ``describe`` declares — names only.

    SPEC 4.1.3 is a security property rather than a convenience: there is
    nowhere in this protocol for a secret to travel, and a document
    carrying a credential *value* is nonconformant. This reads the ``env``
    member and nothing else, so a nonconformant document cannot smuggle one
    past the runner either.
    """
    names: list[str] = []
    for entry in document.get("credentials") or []:
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("env") or "").strip()
        if name and name not in names:
            names.append(name)
    return names


def missing_credentials(
    document: dict[str, Any], environ: dict[str, str] | None = None, bundle_root: Path | None = None
) -> list[str]:
    """Declared credentials with no value in the environment or the bundle's ``.env``.

    ``environ`` is this process's own view. ``bundle_root``, when given, is
    also asked, because the ``load_dotenv`` that would otherwise satisfy a
    declared key runs in the *worker* subprocess
    (``sigrix_runtime.execution.prepare_environment``), never here — so a
    buyer who did exactly what ``.env.example`` says — copy it to ``.env`` —
    saw every declared key reported missing regardless of what the file held.
    The file is asked for presence only, by
    :func:`_credentials_set_in_env_file`: a provider key is never read into
    this process's own environment, which is what keeps SPEC 4.1.3's
    "provider keys stay out of the server process" intact — the same
    constraint that scopes ``entitlement.py``'s own ``.env`` reader to a
    fixed tuple of names that excludes every provider key, drawn here for a
    different, bundle-declared set.
    """
    env = os.environ if environ is None else environ
    missing = [name for name in declared_credentials(document) if not str(env.get(name) or "").strip()]
    if not missing or bundle_root is None:
        return missing
    set_in_file = _credentials_set_in_env_file(bundle_root, missing)
    return [name for name in missing if name not in set_in_file]


def _credentials_set_in_env_file(bundle_root: Path, names: list[str]) -> frozenset[str]:
    """Which of *names* have a non-empty value in the bundle's ``.env``.

    Presence only, by construction: a value read here lives only in the loop
    iteration that strips and checks it, never in this function's return —
    so a provider key cannot leave by way of a value that outlives the call.
    The same four-line stdlib parser ``entitlement.py`` and ``doctor.py``
    each carry their own copy of (standard library only, so ``describe`` and
    ``status`` stay answerable at conformance Level 1 with nothing
    installed), scoped here to whatever this bundle's own document declared
    rather than to a fixed tuple.
    """
    wanted = frozenset(names)
    found: set[str] = set()
    try:
        lines = (bundle_root / ".env").read_text(encoding="utf-8").splitlines()
    except OSError:
        return frozenset()
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key in wanted and value.strip().strip("'\""):
            found.add(key)
    return frozenset(found)


def _refuse_input(key: str, label: str, complaint: str) -> Exception:
    """Refuse one input, naming it the way SPEC 4.2 asks.

    The rule is a SHOULD: a runner rejecting a request "**SHOULD** name the
    offending key in ``message``". Every refusal here already carried the
    key in ``error.detail``, which a client can read but a person cannot —
    and the conformance checker, reading the message, reported the SHOULD
    as not followed.

    So the message carries both, and only where they differ. ``label`` is
    what a person reads ("Your question or brief"); ``key`` is what the
    client sends and what a developer greps for (``prompt``). A declaration
    with no label of its own has ``label == key``, and repeating it would
    read as a stutter rather than as precision.
    """
    named = complaint if label == key else f"{complaint} (input '{key}')"
    return bad_request(f"{label} {named}.", {"key": key})


def validate_run_inputs(document: dict[str, Any], inputs: Any) -> dict[str, Any]:
    """Check a ``run`` body's ``inputs`` map against the declaration (SPEC 4.2).

    A runner **MUST** reject a request omitting a required input or failing
    a declared validation, and **SHOULD** name the offending key. Naming it
    is the whole reason this is worth writing out: a client rendering the
    envelope has a field to put the message beside.

    Undeclared keys are *kept*, not refused. ``inputs`` is an envelope
    (SPEC 4.1.1) whose contents may change between agent versions, and a
    client holding a slightly newer description of the same agent should
    not have its run refused for a key this bundle has not heard of.
    """
    if inputs is None:
        inputs = {}
    if not isinstance(inputs, dict):
        raise bad_request("The 'inputs' member must be an object keyed by input name.")

    resolved: dict[str, Any] = dict(inputs)
    for declaration in document.get("inputs") or []:
        if not isinstance(declaration, dict):
            continue
        key = str(declaration.get("key") or "")
        if not key:
            continue
        supplied = inputs.get(key)
        if supplied is None or (isinstance(supplied, str) and not supplied.strip()):
            default = declaration.get("default")
            if default is not None:
                resolved[key] = default
                continue
            resolved.pop(key, None)
            if declaration.get("required"):
                label = str(declaration.get("label") or key)
                raise _refuse_input(key, label, "is required")
            continue
        _check_value(declaration, key, supplied)
        resolved[key] = supplied
    return resolved


def derive_describe(bundle_root: Path) -> dict[str, Any]:
    """A ``describe`` document built from the bundle's own files.

    Honest about its provenance and thin on purpose — see the module
    docstring for why this path exists at all.
    """
    prompt_key = _prompt_input_key()
    inputs: list[dict[str, Any]] = [
        {
            "key": prompt_key,
            "label": "Your question or brief",
            "type": "text",
            "required": True,
            "default": None,
        }
    ]
    for key in _derived_variable_keys(bundle_root):
        if key == prompt_key:
            continue
        inputs.append(
            {
                "key": key,
                "label": key.replace("_", " ").replace("-", " ").strip().title() or key,
                "type": "text",
                "required": False,
                "default": None,
            }
        )

    config = _derived_config(bundle_root)
    tools = sorted(config.tool_refs) if config is not None else []
    agent: dict[str, Any] = {"name": DERIVED_AGENT_NAME, "version": _starter_version(bundle_root)}
    summary = _derived_summary(config)
    if summary:
        agent["summary"] = summary
    document: dict[str, Any] = {
        "postern": POSTERN_VERSION,
        "agent": agent,
        "inputs": inputs,
        "output": {"type": "text"},
        "capabilities": {
            "tools": tools,
            "write_tools": [tool for tool in tools if tool in WRITE_TOOLS],
        },
        "credentials": _derived_credentials(bundle_root),
    }
    configured = str(os.environ.get("POSTERN_AGENT_ID") or "").strip()
    if is_agent_id(configured):
        document["agent"]["id"] = configured
    return document


# --- Internals -------------------------------------------------------


def _read_shipped(bundle_root: Path) -> dict[str, Any] | None:
    """The distributor's document, or ``None`` when it is absent or unusable.

    A malformed one degrades to the derived form rather than failing the
    verb. ``describe`` is what a client calls first, and a bundle that
    cannot answer it is a bundle a client cannot render at all — a worse
    outcome than a thinner but true answer.
    """
    path = bundle_root / DESCRIBE_FILENAME
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(raw, dict) or not isinstance(raw.get("agent"), dict):
        return None
    if not isinstance(raw.get("inputs"), list):
        return None
    return raw


def _check_value(declaration: dict[str, Any], key: str, value: Any) -> None:
    label = str(declaration.get("label") or key)
    declared_type = str(declaration.get("type") or "text")
    validation = declaration.get("validation")
    validation = validation if isinstance(validation, dict) else {}

    if declared_type == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise _refuse_input(key, label, "must be a number")
        minimum, maximum = validation.get("min"), validation.get("max")
        if isinstance(minimum, (int, float)) and value < minimum:
            raise _refuse_input(key, label, f"must be {minimum} or more")
        if isinstance(maximum, (int, float)) and value > maximum:
            raise _refuse_input(key, label, f"must be {maximum} or less")
        return

    # SPEC 4.1.1: text and select both carry a string, and a client MUST
    # treat a type it does not recognise as text — so a runner validating
    # an unrecognised declared type as text agrees with the client that
    # rendered it.
    if not isinstance(value, str):
        raise _refuse_input(key, label, "must be text")
    if declared_type == "select":
        options = validation.get("options")
        options = [str(option) for option in options] if isinstance(options, list) else []
        if options and value not in options:
            raise _refuse_input(key, label, f"must be one of: {', '.join(options)}")
    max_length = validation.get("max_length")
    if isinstance(max_length, int) and len(value) > max_length:
        raise _refuse_input(key, label, f"must be {max_length} characters or fewer")
    pattern = validation.get("pattern")
    if isinstance(pattern, str) and pattern:
        try:
            matched = re.search(pattern, value) is not None
        except re.error:
            # A validation member that cannot be applied is ignored rather
            # than refused: SPEC 4.1.1 says unrecognised members MUST be
            # ignored, and an unusable one tells a caller even less than an
            # unrecognised one does.
            matched = True
        if not matched:
            raise _refuse_input(key, label, "is not in the expected format")


def _prompt_input_key() -> str:
    """SPEC 4.1.1's reserved input key for the buyer's brief.

    Read from :mod:`sigrix_runtime.execution` where possible, so this and
    the run engine can never name it two different things. ``execution``
    imports ``loader``/``workforce``, both eager on PyYAML — a
    bundle whose virtualenv is not built yet falls back to the literal,
    which is safe because the key is SPEC-fixed vocabulary, not a value
    that drifts.
    """
    try:
        from sigrix_runtime import execution
    except ModuleNotFoundError:
        return "prompt"
    return execution.PROMPT_INPUT_KEY


def _derived_variable_keys(bundle_root: Path) -> list[str]:
    try:
        from sigrix_runtime import configuration

        return sorted(configuration.load_variables(bundle_root))
    except Exception:  # noqa: BLE001 - a derived document degrades, never fails
        return []


def _derived_config(bundle_root: Path) -> execution.RunConfig | None:
    try:
        from sigrix_runtime import execution

        return execution.load_run_config(bundle_root)
    except Exception:  # noqa: BLE001 - a derived document degrades, never fails
        return None


def _derived_summary(config: execution.RunConfig | None) -> str:
    """What the bundle's own config can honestly say about itself.

    Not a description — a shape. A derived document has no access to the
    seller's prose, and inventing a sentence that sounds like one would be
    worse than a count: a client would render it as the listing's summary.
    This says how many members and steps a client is about to run, which is
    true of the files on disk and is the one thing worth knowing before
    spending money on it.
    """
    if config is None or not config.agent_names:
        return ""
    members = len(config.agent_names)
    steps = len(config.task_names)
    kind = "workforce" if config.workforce else "crew"
    return f"A {kind} of {members} member{'s' if members != 1 else ''} running {steps} step{'s' if steps != 1 else ''}."


def _starter_version(bundle_root: Path) -> str:
    try:
        return (bundle_root / "VERSION").read_text(encoding="utf-8").strip() or "0"
    except OSError:
        return "0"


def _derived_credentials(bundle_root: Path) -> list[dict[str, str]]:
    """Read ``.env.example`` for declared keys — the names, never the values.

    That file is generated from the listing's own ``EnvKeyRequirement``
    tuples, which carry exactly the three members SPEC 4.1.3 defines, so
    the comment convention above each key is a real source rather than a
    guess at one. A key that arrives with a value is a *default* rather
    than a requirement — ``doctor.py`` draws the same line — so it is
    skipped here, and nothing in this function ever reads ``.env``.
    """
    path = bundle_root / ".env.example"
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []

    credentials: list[dict[str, str]] = []
    purposes: dict[str, str] = {}
    signup_urls: dict[str, str] = {}
    pending_key = ""
    for line in lines:
        stripped = line.strip()
        comment = _ENV_COMMENT.match(stripped)
        if comment:
            pending_key = comment.group(1)
            purposes[pending_key] = comment.group(2).strip()
            continue
        signup = _SIGNUP_LINE.match(stripped)
        if signup and pending_key:
            signup_urls[pending_key] = signup.group(1)
            continue
        declared = _ENV_LINE.match(stripped)
        if not declared:
            continue
        name = declared.group(1)
        if stripped[len(name) + 1 :].strip():
            continue  # a default, not a requirement
        entry: dict[str, str] = {"env": name}
        if purposes.get(name):
            entry["purpose"] = purposes[name]
        if signup_urls.get(name):
            entry["signup_url"] = signup_urls[name]
        credentials.append(entry)
    return credentials


def is_agent_id(value: str) -> bool:
    """Whether *value* is an agent identifier, octet for octet: nothing is normalised into one."""
    return bool(value) and len(value) <= _AGENT_ID_MAX_LENGTH and _AGENT_ID_PATTERN.fullmatch(value) is not None


__all__ = [
    "AGENT_ID_SHAPE",
    "DERIVED_AGENT_NAME",
    "LOCAL_ID_OWNER",
    "DESCRIBE_FILENAME",
    "WRITE_TOOLS",
    "PosternError",
    "declared_credentials",
    "derive_describe",
    "is_agent_id",
    "local_agent_id",
    "load_describe",
    "missing_credentials",
    "validate_run_inputs",
]
